setx /m JAVA_HOME "%~dp001Enviorment\JDK8"
setx /m HADOOP_HOME "%~dp001Enviorment\hadoop-3.2.1"
setx /m HADOOP_CLASSPATH "%%HADOOP_HOME%%\lib"
setx /m HBASE_HOME "%~dp001Enviorment\hbase-2.3.5"
setx /m HIVE_HOME "%~dp001Enviorment\apache-hive-3.1.2-bin"
setx /m DB_DERBY_HOME "%~dp001Enviorment\db-derby-10.14.2.0-bin"
